# Generated by Django 3.2.6 on 2022-03-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='public_settings',
            new_name='is_public',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='create_user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='goods',
            new_name='comment_goods',
        ),
        migrations.AddField(
            model_name='article',
            name='article_goods',
            field=models.IntegerField(default=0, verbose_name='いいね'),
        ),
    ]
