# Generated by Django 3.2.6 on 2022-03-11 04:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_alter_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_goods',
        ),
        migrations.AddField(
            model_name='article',
            name='good_user',
            field=models.ManyToManyField(related_name='good_user', to=settings.AUTH_USER_MODEL, verbose_name='高評価ユーザー'),
        ),
        migrations.AddField(
            model_name='article',
            name='read_later_user',
            field=models.ManyToManyField(related_name='later_user', to=settings.AUTH_USER_MODEL, verbose_name='後で読むユーザー'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to=settings.AUTH_USER_MODEL, verbose_name='編集者情報'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 11, 13, 17, 58, 495755), verbose_name='公開日'),
        ),
    ]
