# Generated by Django 3.2.6 on 2022-03-11 04:39

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20220311_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='good_user',
            field=models.ManyToManyField(blank=True, related_name='good_user', to=settings.AUTH_USER_MODEL, verbose_name='高評価ユーザー'),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_later_user',
            field=models.ManyToManyField(blank=True, related_name='later_user', to=settings.AUTH_USER_MODEL, verbose_name='後で読むユーザー'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 11, 13, 39, 59, 733095), verbose_name='公開日'),
        ),
    ]
