# Generated by Django 3.2.6 on 2022-03-12 04:09

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_auto_20220312_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='browsing_user',
            field=models.ManyToManyField(blank=True, related_name='browsing_user', to=settings.AUTH_USER_MODEL, verbose_name='閲覧したユーザー'),
        ),
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, default='enemy2.png', null=True, upload_to='article_thumbnail', verbose_name='記事のサムネ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 12, 13, 9, 52, 175015), verbose_name='公開日'),
        ),
    ]
