# Generated by Django 3.2.6 on 2022-03-13 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20220313_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='article_thumbnail', verbose_name='記事のサムネ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 13, 13, 14, 59, 994373), verbose_name='公開日'),
        ),
    ]
