# Generated by Django 3.2.6 on 2022-03-13 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20220313_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='good_count',
            field=models.IntegerField(default=0, verbose_name='いいねの数'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 13, 15, 53, 48, 687321), verbose_name='公開日'),
        ),
    ]
