# Generated by Django 3.2.6 on 2022-03-30 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20220314_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='public_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='更新日'),
        ),
    ]
