# Generated by Django 3.2.6 on 2022-04-06 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_rename_public_date_userarticlerelationship_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='browsing_user',
        ),
        migrations.RemoveField(
            model_name='article',
            name='good_user',
        ),
        migrations.RemoveField(
            model_name='article',
            name='read_later_user',
        ),
        migrations.AlterField(
            model_name='userarticlerelationship',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_related', to='blog.article', verbose_name='記事'),
        ),
    ]
